package com.luxoft.gcmm.calculators;

public enum GCMMOperations {
    COMPUTE_REVENUE_YIELD,
    COMPUTE_PRICE_EARNING_RATIO,
    TRANSACT,
    COMPUTE_INVENTORY_INDEX,
    COMPUTE_VOLUME_WEIGHTED_PRICE
}